//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTIPApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ttipEntities : DbContext
    {
        public ttipEntities()
            : base("name=ttipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<CITY> CITies { get; set; }
        public virtual DbSet<PLACE> PLACEs { get; set; }
        public virtual DbSet<review_> review_ { get; set; }
        public virtual DbSet<photo> photos { get; set; }
    }
}
