//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTIPApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLACE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLACE()
        {
            this.REVIEW = new HashSet<REVIEW>();
        }
    
        public int ID { get; set; }
        public string STORE_NAME { get; set; }
        public string CITY { get; set; }
        public string CATEGORY { get; set; }
        public string EXPLANATION { get; set; }
        public string ADDRESS { get; set; }
        public string DETAIL_IMAGE { get; set; }
    
        public virtual CATEGORY CATEGORY1 { get; set; }
        public virtual CITY CITY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REVIEW> REVIEW { get; set; }
    }
}
