//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTIPApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class review_
    {
        public int REVIEW_NUM { get; set; }
        public int ID { get; set; }
        public string WRITER { get; set; }
        public int SCORE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string substance { get; set; }
    
        public virtual PLACE PLACE { get; set; }
    }
}
